add install script

diff --git a/feces b/feces
--- a/feces
+++ b/feces
@@ -1,23 +1,46 @@
 #!/bin/bash
 
-help () {
-	curl -s https://raw.githubusercontent.com/akpi816218/feces/gitmaster/help/main.txt
-	return
-}
-
 if [[ $# -lt 1 ]] ; then
-	help
-	exit 0
-elif [[ $# -eq 1 && $1 -eq "help" ]] ; then
-	help
-	exit 0
-elif [[ $# -eq 2 && $1 -eq "help" ]] ; then
-	case $2 in
-		"compost")
-			curl -s https://raw.githubusercontent.com/akpi816218/feces/gitmaster/help/compost.txt
-			;;
-		*)
-			printf "Invalid option" && exit 0
-			;;
-	esac
+	curl -s https://raw.githubusercontent.com/akpi816218/feces/gitmaster/help/main.txt && printf "\n" && exit 0
 fi
+
+if [[ $1 -eq "help" ]] ; then
+	if [[ $# -eq 2 ]] ; then
+		case $2 in
+			"compost")
+				curl -s https://raw.githubusercontent.com/akpi816218/feces/gitmaster/help/compost.txt && printf "\n" && exit 0
+				;;
+			"flush")
+				curl -s https://raw.githubusercontentlcom/akpi816218/feces/gitmaster/help/flush.txt && printf "\n" && exit 0
+				;;
+			*)
+				printf "Invalid option\n" && exit 1
+				;;
+		esac
+	elif [[ $# -eq 1 ]] ; then
+		curl -s https://raw.githubusercontent.com/akpi816218/feces/gitmaster/help/main.txt && printf "\n" && exit 0
+	else
+		printf "Too many arguments\n" && exit 1
+	fi
+fi
+
+case $1 in
+	"compost")
+		shift
+		if [[ $# -lt 2 ]] ; then
+			printf "Need 2 arguments to subcommand\n" && exit 1
+		elif ! [[ $1 =~ '^[0-9]+([.][0-9]+)?$' ]] ; then
+			printf "1st argument to subcommand needs to be a number\n" && exit 1
+		else
+			case $2 in
+				"h")
+					;;
+			esac
+		fi
+		;;
+	*)
+		printf "Invalid option\nRun \`feces help\` to see valid options\n" && exit 1
+		;;
+esac
+
+exit 0
